name: zebra_sdk
description: Zebra SDK Plugin
version: 0.2.1+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: zebra_sdk_android

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  zebra_sdk_android:
    # Uncomment the following lines to manually specify the path of the Android plugin implementation:
    # path: ../zebra_sdk_android
    git:
      url: https://github.com/sarisuki-ph/zebra_sdk_flutter.git
      path: zebra_sdk_android
      ref: master

  zebra_sdk_platform_interface:
    # Uncomment the following lines to manually specify the path of the platform interface implementation:
    # path: ../zebra_sdk_platform_interface
    git:
      url: https://github.com/sarisuki-ph/zebra_sdk_flutter.git
      path: zebra_sdk_platform_interface
      ref: master

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
