name: zebra_sdk_android
description: Android implementation of the zebra sdk plugin
version: 0.2.4+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: zebra_sdk
    platforms:
      android:
        package: com.sarisuki.zebra_sdk.plugin
        pluginClass: ZebraSdkPlugin
        dartPluginClass: ZebraSdkAndroid

dependencies:
  flutter:
    sdk: flutter
  zebra_sdk_platform_interface:
    # Uncomment the following lines to manually specify the path of the platform interface implementation:
    # path: ../zebra_sdk_platform_interface
    git:
      url: https://github.com/sarisuki-ph/zebra_sdk_flutter.git
      path: zebra_sdk_platform_interface
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
