name: zebra_sdk_platform_interface
description: A common platform interface for the zebra sdk plugin.
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  very_good_analysis: ^3.0.1
